Feature: Test FCMA Genium Futures and Options.
  As a Ncore User
  I want to make sure that the Futures and Options are generated properly
  So that the right information is available in Downstream and Genium

  Background:
   Given that the tests are to be run on "test" environment


  Scenario Outline: Loading data into the Golden Source DB and checking the xml generated by Ncore adapter
    Given that I prepare to load the "<FutureCsvFile>" and "<GeniumCsvFile>" into db
    #And I load the CsvFile into Golden Source db
   # And I publish the webservice to generate the xml
    #And that I read the message from the queue
    #Then the data should match to the csv submitted
    And I delete the Instrument generated
    Examples:
    |FutureCsvFile|GeniumCsvFile|
    |src\\test\\resources\\data\\DRPS-FutureData1.csv|src\\test\\resources\\data\\Genium Sample Data.csv|
   # |src\\test\\resources\\data\\DRPS-Option-Data.csv|


